### ISSUE TITLE
bitbucket: why are there no snippet for some samples in search results?

### ISSUE THREAD

**Issue by dongbohu** [greenelab/adage-server#230] opened 2017-08-16 15:34 UTC
Bitbucket `#7`: (priority: minor)
https://bitbucket.org/greenelab/adage-server/issues/7/why-are-there-no-snippet-for-some-samples

Searching for certain samples (e.g. `GSM735749 1`) produces a match (so the search is finding something) but no "snippet" of text to go along with it, highlighting where the search term is found.

Need to figure out why the snippets are blank. A search for `pa14` produces several examples.

**Comment by mhuyck** [comment] 2017-08-16 16:57
Cannot reproduce this anymore. It was likely a problem with an index that has long since been repaired.

**Comment by dongbohu** [comment] 2017-08-16 17:21
Should we close it?

**Comment by cgreene** [comment] 2017-08-16 17:25
agree - can't reproduce. closing

**Closed by cgreene** 2017-08-16 17:25 UTC
Labels: bug, from bitbucket
