### ISSUE TITLE
Bug in analysis-detail page when loading E-MEXP-1051 samples and trying to see the heatmap of them

### ISSUE THREAD

**Issue by rzelayafavila** [greenelab/adage-server#253] opened 2017-09-10 19:41 UTC
I got this error when playing around with the UI on the `greenelab.fgtech.com` instance. When I add the 4 samples that appear for experiment E-MEXP-1051(Transcription profiling of Pseudomonas aeruginosa PA14 grown in aerobic or anaerobic conditions in cystic fibrosis sputum with added nitrate ), and then try to see the heatmap, the heatmap does not load, and I see some errors in the JavaScript console.

**Comment by rzelayafavila** [comment] 2017-09-10 19:42
![analysis-detail-screenshot](https://user-images.githubusercontent.com/4641983/30252338-ad2e23a2-963e-11e7-935c-762ae993ca27.png)

**Comment by mhuyck** [comment] 2017-09-13 20:17
This looks very similar to #125, but the cause noted for that issue is not exactly the same here. In this case, we have an "ML Data Source" listed for each sample. This might still be a dup, but I'll have to dig deeper before I know for sure.

**Comment by mhuyck** [comment] 2017-09-18 19:06
More information: if I remove the two aerobic samples (aerobic_NO3_1, aerobic_NO3_2), the heatmap can be drawn again.

**Comment by mhuyck** [comment] 2017-09-18 19:10
There are similar issues with experiment `E-GEOD-26931`. Neither the heatmap nor a volcano plot will draw. In that case, if I remove the four samples with "strain" listed as "E.coli ZK126" then the heatmap recovers.

The pattern seems to be that activity data are missing for some samples. When those samples with missing data are removed then the heatmap works again.

**Comment by mhuyck** [comment] 2017-09-18 19:12
The pattern seems to be that activity data are missing for some samples. When those samples with missing data are removed then the heatmap works again.

Some of these cases seem to be data errors and some may be intentional missing data. In either case, the `adage-server` should be able to handle the missing data gracefully. Perhaps it should even include a message about what samples are affected.

**Comment by mhuyck** [comment] 2017-10-25 00:32
Fixed by #292.

**Closed by mhuyck** 2017-10-25 00:32 UTC
Labels: bug, in progress
